#!/usr/bin/env sh

buildVersion()
{
    ./gradlew clean -PmcVer=$1 --no-daemon
    ./gradlew build -PmcVer=$1 --no-daemon
    ./gradlew mergeJars -PmcVer=$1 --no-daemon
}

buildVersion 1.19
buildVersion 1.18.2
buildVersion 1.18.1
buildVersion 1.17.1
buildVersion 1.16.5
