package com.backsun.lod.objects;

import java.awt.Color;

import com.backsun.lod.enums.ColorDirection;
import com.backsun.lod.enums.LodCorner;
import com.backsun.lod.enums.LodLocation;

import net.minecraft.util.math.ChunkPos;

/**
 * This object contains position
 * and color data for an LOD object.
 * 
 * @author James Seibel
 * @version 03-24-2021
 */
public class LodChunk
{
	/** how many different pieces of data are in one line */
	private static final int DATA_DELIMITER_COUNT = 28;

	/** This is what separates each piece of data in the toData method */
	public static final char DATA_DELIMITER = ',';
	
	public static final int WIDTH = 16;
	
	
	
	/** The x coordinate of the chunk. */
	public int x;
	/** The z coordinate of the chunk. */
	public int z;
	
	// each short is the height of
	// that 8th of the chunk.
	public short top[];
	public short bottom[];
	
	/** The average color of each 6 cardinal directions */
	public Color colors[];
	
	/** If true that means this LodChunk is just a placeholder and
	 * no LOD has been generated for this chunk location */
	private boolean emptyPlaceholder = false;
	
	
	
	
	
	
	//==============//
	// constructors //
	//==============//
	
	/**
	 * Create an empty invisible LodChunk at (0,0)
	 */
	public LodChunk()
	{
		emptyPlaceholder = true;
		
		x = 0;
		z = 0;
		
		top = new short[4];
		bottom = new short[4];
		colors = new Color[6];
		
		// by default have the colors invisible
		for(ColorDirection dir : ColorDirection.values())
		{
			colors[dir.value] = new Color(0, 0, 0, 0);
		}
	}
	
	/**
	 * Creates an LodChunk from the string
	 * generated by the toData method.
	 * 
	 * @throws IllegalArgumentException if the data isn't valid to create a LodChunk
	 * @throws NumberFormatException if the data can't be converted into an int at any point
	 */
	public LodChunk(String data) throws IllegalArgumentException, NumberFormatException
	{
		/*
		 * data format:
		 * x, z, top data, bottom data, rgb color data
		 * 
		 * example:
		 * 5,8, 4,4,4,4, 0,0,0,0, 255,255,255, 255,255,255, 255,255,255, 255,255,255, 255,255,255, 255,255,255,
		 */
		
		emptyPlaceholder = false;
		
		// make sure there are the correct number of entries
		// in the data string (28)
		int count = 0;
		
		for(int i = 0; i < data.length(); i++)
		{
			if(data.charAt(i) == DATA_DELIMITER)
			{
				count++;
			}
		}
		
		if(count != DATA_DELIMITER_COUNT)
		{
			throw new IllegalArgumentException("LodChunk constructor givin an invalid string. The data given had " + count + " delimiters when it should have had " + DATA_DELIMITER_COUNT + ".");
		}
		
		
		
		// index we will use when going through the String
		int index = 0;
		int lastIndex = 0;
		
		
		
		// x and z position
		index = data.indexOf(DATA_DELIMITER, 0);
		x = Integer.parseInt(data.substring(0,index));
		
		lastIndex = index;
		index = data.indexOf(DATA_DELIMITER, lastIndex + 1);
		z = Integer.parseInt(data.substring(lastIndex+1,index));
		
		
		
		// top
		top = new short[4];
		for(LodLocation loc : LodLocation.values())
		{
			lastIndex = index;
			index = data.indexOf(DATA_DELIMITER, lastIndex + 1);
			
			top[loc.value] = Short.parseShort(data.substring(lastIndex+1,index));
		}
		
		
		// bottom
		bottom = new short[4];
		for(LodLocation loc : LodLocation.values())
		{
			lastIndex = index;
			index = data.indexOf(DATA_DELIMITER, lastIndex + 1);
			
			bottom[loc.value] = Short.parseShort(data.substring(lastIndex+1,index));
		}
		
		
		// color
		colors = new Color[6];
		for(ColorDirection dir : ColorDirection.values())
		{
			int red = 0;
			int green = 0;
			int blue = 0;
			
			// get r,g,b
			for(int i = 0; i < 3; i++)
			{
				lastIndex = index;
				index = data.indexOf(DATA_DELIMITER, lastIndex + 1);
				
				String raw = "";
				switch(i)
				{
				case 0:
					raw = data.substring(lastIndex+1,index);
					red = Short.parseShort(raw);
					break;
				case 1:
					raw = data.substring(lastIndex+1,index);
					green = Short.parseShort(raw);
					break;
				case 2:
					raw = data.substring(lastIndex+1,index);
					blue = Short.parseShort(raw);
					break;
				}
			}
			
			colors[dir.value] = new Color(red, green, blue);
		}
	}
	
	/**
	 * Create a LodChunk from the given values.
	 */
	public LodChunk(ChunkPos pos, short[] newTop, short[] newBottom, Color[] newColors)
	{
		emptyPlaceholder = false;
		
		x = pos.x;
		z = pos.z;
		
		top = newTop;
		bottom = newBottom;
		colors = newColors;
	}
	
	
	
	
	
	
	//================//
	// misc functions //
	//================//
	
	/**
	 * Returns true if this LodChunk is an emptyPlaceholder
	 */
	public boolean isPlaceholder()
	{
		return emptyPlaceholder;
	}
	
	/**
	 * Returns true if this LOD is either invisible
	 * from every direction, doesn't have a valid height, 
	 * or is an emptyPlaceholder.
	 */
	public boolean isLodEmpty()
	{
		if (emptyPlaceholder)
			return true;
		
		for(LodCorner corner : LodCorner.values())
			if(top[corner.value] != -1 || bottom[corner.value] != -1)
				// at least one corner is valid
				return false;
		
		Color invisible = new Color(0,0,0,0);
		for(ColorDirection dir : ColorDirection.values())
			if(!colors[dir.value].equals(invisible))
				// at least one direction has a non-invisible color
				return false;
		
		return true;
	}
	
	
	
	
	
	//========//
	// output //
	//========//
	
	
	
	/**
	 * Outputs all data in csv format
	 * with the given delimiter.
	 * <br>
	 * Exports data in the form:
	 * <br>
	 * x, z, top data, bottom data, rgb color data
	 * 
	 * <br>
	 * example output:
	 * <br>
	 * 5,8, 4,4,4,4, 0,0,0,0 255,255,255, 255,255,255, 255,255,255, 255,255,255, 255,255,255, 255,255,255,
	 */
	public String toData()
	{
		String s = "";
		
		s += Integer.toString(x) + DATA_DELIMITER +  Integer.toString(z) + DATA_DELIMITER;
		
		for(int i = 0; i < top.length; i++)
		{
			s += Short.toString(top[i]) + DATA_DELIMITER;
		}
		
		for(int i = 0; i < bottom.length; i++)
		{
			s += Short.toString(bottom[i]) + DATA_DELIMITER;
		}
		
		for(int i = 0; i < colors.length; i++)
		{
			s += Integer.toString(colors[i].getRed()) + DATA_DELIMITER + Integer.toString(colors[i].getGreen()) + DATA_DELIMITER + Integer.toString(colors[i].getBlue()) + DATA_DELIMITER;
		}
		
		return s;
	}
	
	
	@Override
	public String toString()
	{
		String s = "";
		
		s += "x: " + x + " z: " + z + "\t";
		
		s += "(" + colors[ColorDirection.TOP.value].getRed() + ", " + colors[ColorDirection.TOP.value].getGreen() + ", " + colors[ColorDirection.TOP.value].getBlue() + ")";
		
		return s;
	}
}
